add products markup
alexxxusachev888/ice-cream-shop pull request #3
Opened 2022-10-07 17:06 UTC by Eugene-Hlushak

2022-10-07 17:52 UTC, alexxxusachev888 requested changes
button

2022-10-07 17:52 UTC, alexxxusachev888 commented on src/partials/products.html
> +          <button class="read-more">
здається треба додати тегу button атрибут type="button"

2022-10-07 17:52 UTC, alexxxusachev888 commented on src/partials/products.html
> +<section class="section">
я б назвав класс у секції "products" та у тегу p and h2, але мені здається це не принципово))

2022-10-07 18:56 UTC, Eugene-Hlushak commented on src/partials/products.html
> +<section class="section">
У нас у двох секціях - products i about - є однакова структура: над-заголовок <p> і сам заголовок <h2>, і відповідні параметри у них однакові. Їх можна зробити як компонентний клас, як container. Можу зайнятися цим.

2022-10-07 18:58 UTC, Eugene-Hlushak commented on src/partials/products.html
> +          <button class="read-more">
Виправлено

2022-10-08 07:20 UTC, alexxxusachev888 approved these changes
Гарно)

2022-10-08 07:23 UTC, alexxxusachev888 commented on src/partials/products.html
> +<section class="section">
Зараз перевірю пул-реквест Дениса та відпишусь)

2022-10-08 07:23 UTC, merged